Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -94,7 +94,22 @@ jobs:
           
           UUID=$(security cms -D -i $RUNNER_TEMP/provisioning_profile.mobileprovision | plutil -extract UUID raw -)
           mv $RUNNER_TEMP/provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
-
+          
+          # Confirm installation
+          if [ -f ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision ]; then
+            echo "Provisioning profile installed successfully."
+          else
+            echo "Failed to install provisioning profile."
+            exit 1
+          fi
+      
+          # List installed profiles for verification
+          echo "Listing installed provisioning profiles:"
+          ls ~/Library/MobileDevice/Provisioning\ Profiles
+      
+          # Display information about the installed profile
+          security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
+          
       # - name: Prepare exportOptions.plist
       #   run: | 
       #     cd ios &&
@@ -157,6 +172,8 @@ jobs:
         run: |
           security delete-keychain ~/Library/Keychains/build.keychain
           security delete-keychain ~/Library/Keychains/login.keychain-db
-          rm ~/Library/MobileDevice/Provisioning\ Profiles/provisioning_profile.mobileprovision
-          rm ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
+          rm -f /Library/MobileDevice/Provisioning\ Profiles/*
+          
+          # rm ~/Library/MobileDevice/Provisioning\ Profiles/provisioning_profile.mobileprovision
+          # rm ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
 
