Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -22,54 +22,54 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
        
-      # - uses: actions/setup-node@master
-      #   with:
-      #     node-version: '21.2.0'
+      - uses: actions/setup-node@master
+        with:
+          node-version: '21.2.0'
         
-      # - name: Install dependencies
-      #   run: npm install
+      - name: Install dependencies
+        run: npm install
       
-      # - name: 'Create env file'
-      #   run: |
-      #     touch .env
-      #     echo apiUrlDevelop=${{ secrets.APIURLDEVELOP }} >> .env
-      #     echo facebookAppDisplayName=${{ secrets.FACEBOOKAPPDISPLAYNAME }} >> .env
-      #     echo facebookAppId=${{ secrets.FACEBOOKAPPID }} >> .env
-      #     echo facebookClientToken=${{ secrets.FACEBOOKCLIENTTOKEN }} >> .env
-      #     echo projectNumber=${{ secrets.PROJECTNUMBER }} >> .env
-      #     echo clientIdKey=${{ secrets.CLIENTIDKEY }} >> .env
+      - name: 'Create env file'
+        run: |
+          touch .env
+          echo apiUrlDevelop=${{ secrets.APIURLDEVELOP }} >> .env
+          echo facebookAppDisplayName=${{ secrets.FACEBOOKAPPDISPLAYNAME }} >> .env
+          echo facebookAppId=${{ secrets.FACEBOOKAPPID }} >> .env
+          echo facebookClientToken=${{ secrets.FACEBOOKCLIENTTOKEN }} >> .env
+          echo projectNumber=${{ secrets.PROJECTNUMBER }} >> .env
+          echo clientIdKey=${{ secrets.CLIENTIDKEY }} >> .env
        
-      # - name: Putting data google service Dev file
-      #   env:
-      #     DATA: ${{ secrets.GOOGLE_SERVICES_PLIST_DEV }}
-      #   run: |
-      #     touch /Users/runner/work/parenting-app-bebbo-mobile/parenting-app-bebbo-mobile/ios/GoogleServices/Development/GoogleService-Info.plist
-      #     echo -n $DATA | base64 -d > /Users/runner/work/parenting-app-bebbo-mobile/parenting-app-bebbo-mobile/ios/GoogleServices/Development/GoogleService-Info.plist
+      - name: Putting data google service Dev file
+        env:
+          DATA: ${{ secrets.GOOGLE_SERVICES_PLIST_DEV }}
+        run: |
+          touch /Users/runner/work/parenting-app-bebbo-mobile/parenting-app-bebbo-mobile/ios/GoogleServices/Development/GoogleService-Info.plist
+          echo -n $DATA | base64 -d > /Users/runner/work/parenting-app-bebbo-mobile/parenting-app-bebbo-mobile/ios/GoogleServices/Development/GoogleService-Info.plist
        
-      # - name: Install CocoaPods
-      #   run: |
-      #     sudo gem install cocoapods
+      - name: Install CocoaPods
+        run: |
+          sudo gem install cocoapods
 
-      # - name: Set environment variable for modular headers
-      #   run: echo "USE_MODULAR_HEADERS=true" >> $GITHUB_ENV
+      - name: Set environment variable for modular headers
+        run: echo "USE_MODULAR_HEADERS=true" >> $GITHUB_ENV
 
-      # - name: Modify Podfile for Modular Headers
-      #   run: |
-      #     cd ios  # Update this path if necessary
-      #     sed -i '' '1s/^/if ENV["USE_MODULAR_HEADERS"] == "true"\nuse_modular_headers!\nend\n\n/' Podfile
-      #     cat Podfile
+      - name: Modify Podfile for Modular Headers
+        run: |
+          cd ios  # Update this path if necessary
+          sed -i '' '1s/^/if ENV["USE_MODULAR_HEADERS"] == "true"\nuse_modular_headers!\nend\n\n/' Podfile
+          cat Podfile
 
-      # - name: Install pod dependencies
-      #   run: | 
-      #     cd ios && rm -rf Pods Podfile.lock && pod install --repo-update
+      - name: Install pod dependencies
+        run: | 
+          cd ios && rm -rf Pods Podfile.lock && pod install --repo-update
 
-      # - name: Authenticate with Apple Developer account
-      #   env:
-      #     APPLE_ID: ${{ secrets.APPLE_ID }}
-      #     APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
-      #   run: |
-      #     echo "machine apple.com login $APPLE_ID password $APP_SPECIFIC_PASSWORD" > ~/.netrc
-      #     security add-internet-password -a $APPLE_ID -s idmsa.apple.com -w $APP_SPECIFIC_PASSWORD -T /usr/bin/security
+      - name: Authenticate with Apple Developer account
+        env:
+          APPLE_ID: ${{ secrets.APPLE_ID }}
+          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
+        run: |
+          echo "machine apple.com login $APPLE_ID password $APP_SPECIFIC_PASSWORD" > ~/.netrc
+          security add-internet-password -a $APPLE_ID -s idmsa.apple.com -w $APP_SPECIFIC_PASSWORD -T /usr/bin/security
 
       - name: Create and unlock keychain
         run: |
@@ -80,36 +80,6 @@ jobs:
           security list-keychains -d user
           security show-keychain-info build.keychain || echo "Keychain info not available"
 
-          # security create-keychain -p $KEY_PWD build.keychain
-          # security default-keychain -s build.keychain
-          # security unlock-keychain -p $KEY_PWD build.keychain
-          # security unlock-keychain -p $KEY_PWD
-          # security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
-
-          # # // Add my keychain file to list of keychain
-          # security list-keychains -s "echo 'echo security list-keychains | xargs ~/Library/Keychains/build.keychain' | xargs -n1 | sort -u | xargs"
-           
-          # # // Lock keychain, just in case it was already unlock, gui user and ssh user from Jenkins unlock request are not playing well together, go figure why, one hell of Apple way
-          # security lock-keychain ~/Library/Keychains/build.keychain
-           
-          # # // Do the same for the login keychain
-          # security lock-keychain login
-           
-          # # // Unlock my keychain
-          # security unlock-keychain -p $KEY_PWD ~/Library/Keychains/build.keychain
-           
-          # # // Unlock login.keychain too, I have no idea why thi is required but you have to do it, another of Apple secrets
-          # security unlock-keychain -p $KEY_PWD login
-           
-          # # // Keep keychain unlock
-          # security set-keychain-settings ~/Library/Keychains/build.keychain
-           
-          # # // Allow apple signing tool to access keychain
-          # security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEY_PWD ~/Library/Keychains/build.keychain
-           
-          # # // Set my keychain as the default one
-          # security default-keychain -s ~/Library/Keychains/build.keychain
-                     
       - name: Install Certificate
         run: |
           # Decode and install certificate
@@ -142,77 +112,74 @@ jobs:
           # # Display information about the installed profile
           # security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
           
-      # - name: Prepare exportOptions.plist
-      #   run: | 
-      #     cd ios &&
-      #     cat > exportOptions.plist <<EOL
-      #       <?xml version="1.0" encoding="UTF-8"?>
-      #       <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
-      #       <plist version="1.0">
-      #       <dict>
-      #         <key>compileBitcode</key>
-      #         <false/>
-      #         <key>destination</key>
-      #         <string>export</string>
-      #         <key>method</key>
-      #         <string>enterprise</string>
-      #         <key>signingStyle</key>
-      #         <string>automatic</string>
-      #         <key>stripSwiftSymbols</key>
-      #         <true/>
-      #         <key>teamID</key>
-      #         <string>$TEAM_ID</string>
-      #         <key>signingCertificate</key>
-      #         <string>Apple Distribution</string>
-      #         <key>provisioningProfiles</key>
-      #         <dict>
-      #           <key>com.datamatics.bebbo</key>
-      #           <string>iOS Distribution: Datamatics Global Services Limited</string>
-      #         </dict>
-              # <key>thinning</key>
-              # <string>&lt;none&gt;</string>
-      #         </dict>
-      #       </plist>
-      #       EOL
+      - name: Prepare exportOptions.plist
+        run: | 
+          cd ios &&
+          cat > exportOptions.plist <<EOL
+            <?xml version="1.0" encoding="UTF-8"?>
+            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+            <plist version="1.0">
+            <dict>
+              <key>compileBitcode</key>
+              <false/>
+              <key>destination</key>
+              <string>export</string>
+              <key>method</key>
+              <string>enterprise</string>
+              <key>signingStyle</key>
+              <string>automatic</string>
+              <key>stripSwiftSymbols</key>
+              <true/>
+              <key>teamID</key>
+              <string>$TEAM_ID</string>
+              <key>signingCertificate</key>
+              <string>Apple Distribution</string>
+              <key>provisioningProfiles</key>
+              <key>com.datamatics.bebbo</key>
+              <string>iOS Distribution: Datamatics Global Services Limited</string>
+              <key>thinning</key>
+              <string>&lt;none&gt;</string>
+              </dict>
+            </plist>
+            EOL
 
-      # - name: Prepare exportOptions.plist
-      #   run: | 
-      #     cd ios
-      #       if [ -f exportOptions.plist ]; then
-      #         echo "exportOptions.plist created successfully."
-      #         cat exportOptions.plist  # Optionally print the contents for verification
-      #       else
-      #         echo "Failed to create exportOptions.plist."
-      #         exit 1
-      #       fi
+      - name: Prepare exportOptions.plist
+        run: | 
+          cd ios
+            if [ -f exportOptions.plist ]; then
+              echo "exportOptions.plist created successfully."
+              cat exportOptions.plist  # Optionally print the contents for verification
+            else
+              echo "Failed to create exportOptions.plist."
+              exit 1
+            fi
         
-      # - name: Select Xcode
-      #   run: sudo xcode-select -switch /Applications/Xcode_15.1.app
+      - name: Select Xcode
+        run: sudo xcode-select -switch /Applications/Xcode_15.1.app
      
-      # - name: Xcode Version
-      #   run: /usr/bin/xcodebuild -version
+      - name: Xcode Version
+        run: /usr/bin/xcodebuild -version
       
-      # - name: Create build folder
-      #   run: |
-      #     cd ./ios && mkdir -p build && mkdir -p staging
+      - name: Create build folder
+        run: |
+          cd ./ios && mkdir -p build && mkdir -p staging
      
-      # - name: Build Archive
-      #   run: |
-      #     cd ios && xcodebuild archive -workspace "ParentBuddyApp.xcworkspace" -scheme "ParentBuddyAppDev" -configuration "Release" -sdk iphoneos -UseModernBuildSystem=0 IPHONEOS_DEPLOYMENT_TARGET=12.0 -archivePath "./build/ParentBuddyApp.xcarchive" -allowProvisioningUpdates
+      - name: Build Archive
+        run: |
+          cd ios && xcodebuild archive -workspace "ParentBuddyApp.xcworkspace" -scheme "ParentBuddyAppDev" -configuration "Release" -sdk iphoneos -UseModernBuildSystem=0 IPHONEOS_DEPLOYMENT_TARGET=12.0 -archivePath "./build/ParentBuddyApp.xcarchive" -allowProvisioningUpdates
         
-      # - name: Export Archive
-      #   run: |
-      #     cd ios &&
-      #     xcodebuild -verbose -exportArchive -allowProvisioningUpdates \
-      #     -archivePath "./build/ParentBuddyApp.xcarchive" \
-      #     -exportPath "$ARTIFACT_PATH_STAGING" \
-      #     -exportOptionsPlist "exportOptions.plist"
+      - name: Export Archive
+        run: |
+          cd ios && xcodebuild -verbose -exportArchive -allowProvisioningUpdates \
+          -archivePath "./build/ParentBuddyApp.xcarchive" \
+          -exportPath "$ARTIFACT_PATH_STAGING" \
+          -exportOptionsPlist "exportOptions.plist"
         
-      # - name: Upload Artifacts
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: Bebbo.ipa
-      #     path: $ARTIFACT_PATH_STAGING
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: Bebbo.ipa
+          path: $ARTIFACT_PATH_STAGING
       
       - name: Clean up keychain and provisioning profile
         if: ${{ always() }}
