Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -22,86 +22,86 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
        
-      # - uses: actions/setup-node@master
-      #   with:
-      #     node-version: '21.2.0'
+      - uses: actions/setup-node@master
+        with:
+          node-version: '21.2.0'
         
-      # - name: Install dependencies
-      #   run: npm install
+      - name: Install dependencies
+        run: npm install
       
-      # - name: 'Create env file'
-      #   run: |
-      #     touch .env
-      #     echo apiUrlDevelop=${{ secrets.APIURLDEVELOP }} >> .env
-      #     echo facebookAppDisplayName=${{ secrets.FACEBOOKAPPDISPLAYNAME }} >> .env
-      #     echo facebookAppId=${{ secrets.FACEBOOKAPPID }} >> .env
-      #     echo facebookClientToken=${{ secrets.FACEBOOKCLIENTTOKEN }} >> .env
-      #     echo projectNumber=${{ secrets.PROJECTNUMBER }} >> .env
-      #     echo clientIdKey=${{ secrets.CLIENTIDKEY }} >> .env
+      - name: 'Create env file'
+        run: |
+          touch .env
+          echo apiUrlDevelop=${{ secrets.APIURLDEVELOP }} >> .env
+          echo facebookAppDisplayName=${{ secrets.FACEBOOKAPPDISPLAYNAME }} >> .env
+          echo facebookAppId=${{ secrets.FACEBOOKAPPID }} >> .env
+          echo facebookClientToken=${{ secrets.FACEBOOKCLIENTTOKEN }} >> .env
+          echo projectNumber=${{ secrets.PROJECTNUMBER }} >> .env
+          echo clientIdKey=${{ secrets.CLIENTIDKEY }} >> .env
        
-      # - name: Putting data google service Dev file
-      #   env:
-      #     DATA: ${{ secrets.GOOGLE_SERVICES_PLIST_DEV }}
-      #   run: |
-      #     touch /Users/runner/work/parenting-app-bebbo-mobile/parenting-app-bebbo-mobile/ios/GoogleServices/Development/GoogleService-Info.plist
-      #     echo -n $DATA | base64 -d > /Users/runner/work/parenting-app-bebbo-mobile/parenting-app-bebbo-mobile/ios/GoogleServices/Development/GoogleService-Info.plist
+      - name: Putting data google service Dev file
+        env:
+          DATA: ${{ secrets.GOOGLE_SERVICES_PLIST_DEV }}
+        run: |
+          touch /Users/runner/work/parenting-app-bebbo-mobile/parenting-app-bebbo-mobile/ios/GoogleServices/Development/GoogleService-Info.plist
+          echo -n $DATA | base64 -d > /Users/runner/work/parenting-app-bebbo-mobile/parenting-app-bebbo-mobile/ios/GoogleServices/Development/GoogleService-Info.plist
        
-      # - name: Install CocoaPods
-      #   run: |
-      #     sudo gem install cocoapods
+      - name: Install CocoaPods
+        run: |
+          sudo gem install cocoapods
 
-      # - name: Set environment variable for modular headers
-      #   run: echo "USE_MODULAR_HEADERS=true" >> $GITHUB_ENV
+      - name: Set environment variable for modular headers
+        run: echo "USE_MODULAR_HEADERS=true" >> $GITHUB_ENV
 
-      # - name: Modify Podfile for Modular Headers
-      #   run: |
-      #     cd ios  # Update this path if necessary
-      #     sed -i '' '1s/^/if ENV["USE_MODULAR_HEADERS"] == "true"\nuse_modular_headers!\nend\n\n/' Podfile
-      #     cat Podfile
+      - name: Modify Podfile for Modular Headers
+        run: |
+          cd ios  # Update this path if necessary
+          sed -i '' '1s/^/if ENV["USE_MODULAR_HEADERS"] == "true"\nuse_modular_headers!\nend\n\n/' Podfile
+          cat Podfile
 
-      # - name: Install pod dependencies
-      #   run: | 
-      #     cd ios && rm -rf Pods Podfile.lock && pod install --repo-update
+      - name: Install pod dependencies
+        run: | 
+          cd ios && rm -rf Pods Podfile.lock && pod install --repo-update
 
-      # - name: Authenticate with Apple Developer account
-      #   env:
-      #     APPLE_ID: ${{ secrets.APPLE_ID }}
-      #     APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
-      #   run: |
-      #     echo "machine apple.com login $APPLE_ID password $APP_SPECIFIC_PASSWORD" > ~/.netrc
-      #     security add-internet-password -a $APPLE_ID -s idmsa.apple.com -w $APP_SPECIFIC_PASSWORD -T /usr/bin/security
+      - name: Authenticate with Apple Developer account
+        env:
+          APPLE_ID: ${{ secrets.APPLE_ID }}
+          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
+        run: |
+          echo "machine apple.com login $APPLE_ID password $APP_SPECIFIC_PASSWORD" > ~/.netrc
+          security add-internet-password -a $APPLE_ID -s idmsa.apple.com -w $APP_SPECIFIC_PASSWORD -T /usr/bin/security
 
-      # - name: Create and unlock keychain
-      #   run: |
-      #     security create-keychain -p $KEY_PWD build.keychain
-      #     security default-keychain -s build.keychain
-      #     security unlock-keychain -p $KEY_PWD build.keychain
-      #     security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
+      - name: Create and unlock keychain
+        run: |
+          security create-keychain -p $KEY_PWD build.keychain
+          security default-keychain -s build.keychain
+          security unlock-keychain -p $KEY_PWD build.keychain
+          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
 
-      # - name: Install Certificate
-      #   run: |
-      #     # Decode and install certificate
-      #     echo -n "$DISTRIBUTION_CERTIFICATE" | base64 -Dd -o certificate.p12
-      #     security import certificate.p12 -k ~/Library/Keychains/build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
-      #     security set-key-partition-list -S apple-tool:,apple: -s -k $CERTIFICATE_PASSWORD ~/Library/Keychains/build.keychain
+      - name: Install Certificate
+        run: |
+          # Decode and install certificate
+          echo -n "$DISTRIBUTION_CERTIFICATE" | base64 -Dd -o certificate.p12
+          security import certificate.p12 -k ~/Library/Keychains/build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
+          security set-key-partition-list -S apple-tool:,apple: -s -k $CERTIFICATE_PASSWORD ~/Library/Keychains/build.keychain
       
-      # - name: Install Provisioning
-      #   run: |
-      #     # Install provisioning profile
-      #     echo -n "$DISTRIBUTION_PROFILE_PROD" | base64 -Dd -o $RUNNER_TEMP/provisioning_profile.mobileprovision
-      #     mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-      #     cp $RUNNER_TEMP/provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles
+      - name: Install Provisioning
+        run: |
+          # Install provisioning profile
+          echo -n "$DISTRIBUTION_PROFILE_PROD" | base64 -Dd -o $RUNNER_TEMP/provisioning_profile.mobileprovision
+          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
+          cp $RUNNER_TEMP/provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles
           
-      #     UUID=$(security cms -D -i $RUNNER_TEMP/provisioning_profile.mobileprovision | plutil -extract UUID raw -)
-      #     mv $RUNNER_TEMP/provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
+          UUID=$(security cms -D -i $RUNNER_TEMP/provisioning_profile.mobileprovision | plutil -extract UUID raw -)
+          mv $RUNNER_TEMP/provisioning_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
           
-      #     # Confirm installation
-      #     if [ -f ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision ]; then
-      #       echo "Provisioning profile installed successfully."
-      #     else
-      #       echo "Failed to install provisioning profile."
-      #       exit 1
-      #     fi
+          # Confirm installation
+          if [ -f ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision ]; then
+            echo "Provisioning profile installed successfully."
+          else
+            echo "Failed to install provisioning profile."
+            exit 1
+          fi
       
           # # List installed profiles for verification
           # echo "Listing installed provisioning profiles:"
@@ -151,43 +151,42 @@ jobs:
               echo "Failed to create exportOptions.plist."
               exit 1
             fi
-
         
-      # - name: Select Xcode
-      #   run: sudo xcode-select -switch /Applications/Xcode_15.1.app
+      - name: Select Xcode
+        run: sudo xcode-select -switch /Applications/Xcode_15.1.app
      
-      # - name: Xcode Version
-      #   run: /usr/bin/xcodebuild -version
+      - name: Xcode Version
+        run: /usr/bin/xcodebuild -version
       
-      # - name: Create build folder
-      #   run: |
-      #     cd ./ios && mkdir -p build && mkdir -p staging
+      - name: Create build folder
+        run: |
+          cd ./ios && mkdir -p build && mkdir -p staging
      
-      # - name: Build Archive
-      #   run: |
-      #     cd ios && xcodebuild archive -workspace "ParentBuddyApp.xcworkspace" -scheme "ParentBuddyAppDev" -configuration "Release" -sdk iphoneos -UseModernBuildSystem=0 IPHONEOS_DEPLOYMENT_TARGET=12.0 -archivePath "./build/ParentBuddyApp.xcarchive" -allowProvisioningUpdates
+      - name: Build Archive
+        run: |
+          cd ios && xcodebuild archive -workspace "ParentBuddyApp.xcworkspace" -scheme "ParentBuddyAppDev" -configuration "Release" -sdk iphoneos -UseModernBuildSystem=0 IPHONEOS_DEPLOYMENT_TARGET=12.0 -archivePath "./build/ParentBuddyApp.xcarchive" -allowProvisioningUpdates
         
-      # - name: Export Archive
-      #   run: |
-      #     cd ios &&
-      #     xcodebuild -exportArchive -allowProvisioningUpdates \
-      #     -archivePath "./build/ParentBuddyApp.xcarchive" \
-      #     -exportPath "$ARTIFACT_PATH_STAGING" \
-      #     -exportOptionsPlist "exportOptions.plist"
+      - name: Export Archive
+        run: |
+          cd ios &&
+          xcodebuild -exportArchive -allowProvisioningUpdates \
+          -archivePath "./build/ParentBuddyApp.xcarchive" \
+          -exportPath "$ARTIFACT_PATH_STAGING" \
+          -exportOptionsPlist "exportOptions.plist"
         
-      # - name: Upload Artifacts
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: Bebbo.ipa
-      #     path: $ARTIFACT_PATH_STAGING
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: Bebbo.ipa
+          path: $ARTIFACT_PATH_STAGING
       
-      # - name: Clean up keychain and provisioning profile
-      #   if: ${{ always() }}
-      #   run: |
-      #     security delete-keychain ~/Library/Keychains/build.keychain
-      #     security delete-keychain ~/Library/Keychains/login.keychain-db
-      #     rm -f /Library/MobileDevice/Provisioning\ Profiles/*
+      - name: Clean up keychain and provisioning profile
+        if: ${{ always() }}
+        run: |
+          security delete-keychain ~/Library/Keychains/build.keychain
+          security delete-keychain ~/Library/Keychains/login.keychain-db
+          rm -f /Library/MobileDevice/Provisioning\ Profiles/*
           
-      #     # rm ~/Library/MobileDevice/Provisioning\ Profiles/provisioning_profile.mobileprovision
-      #     # rm ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
+          # rm ~/Library/MobileDevice/Provisioning\ Profiles/provisioning_profile.mobileprovision
+          # rm ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
 
